### ISSUE TITLE
Make KubeletConfig Parameters configurable

### ISSUE THREAD

**Issue by cwilkers** [openshift-kni/performance-addon-operators#110]
It may become necessary to expose certain parameters within the KubeletConfig, e.g. `topologyManagerPolicy` which are currently hard-coded.

**Comment by cwilkers** [comment]
WIP https://github.com/cwilkers/performance-addon-operators/tree/kubeletconfig

**Comment by simon3z** [comment]
@MarSik @slintes PTAL

**Comment by slintes** [comment]
@cwilkers please create a PR with it

**Comment by cwilkers** [comment]
@slintes  Linking WIP PR: 

https://github.com/openshift-kni/performance-addon-operators/pull/117

**Comment by cwilkers** [comment]
Resolved, thanks!

**Comment by slintes** [comment]
thanks for implementing it :+1:
