### ISSUE TITLE
kubelet stopped working after applying the wrong performanceprofile

### ISSUE THREAD

**Issue by tripledes** [openshift-kni/performance-addon-operators#236]
After applying a performanceprofile that was setting reserved cpus to a set of cpus that the machine didn't have, the kubelet could not start any more with the following message:

```
server.go:274] failed to run Kubelet: Invalid cpuset "9-15" specified by --reserved-cpus
```

I understand this is a user mistake but I think this is one that the performance operator could make some sanity checks before applying the configuration.

**Comment by slintes** [comment]
Thanks for reporting this.
I don't think we can do such checks. We don't change the config on the node directly, we just create a `KubeletConfig`, which is processed by other controllers. We don't know and can't check available CPUs of all nodes the config is targeting.

**Comment by tripledes** [comment]
Hey @slintes I see, if there's nothing you can check I guess we can close this one. :+1:
