### ISSUE TITLE
attempt to validate mcp has picked up chnages before issuing "unpause"

### ISSUE THREAD

**Issue by davidvossel** [openshift-kni/performance-addon-operators#35]
from this discussion https://github.com/openshift-kni/performance-addon-operators/pull/25#discussion_r364460755

lets see if there's a way to introspect the mcp to determine whether it has picked up the configs we've posted before unpausing it.  

Maybe we won't be able to introspect all changes were picked up, but at least seeing that the changes we can check have been picked up gives us some assurance that the mcp has at least been updated.

This is mostly an optimization. The worst case scenario is we reboot a node twice to apply changes if we unpause too early.

**Comment by slintes** [comment]
we don't create the MCP in the operator code anymore, so this is obsolete

/close
