### ISSUE TITLE
Can we get clarity on this setting?

### ISSUE THREAD

**Issue by atheurer** [openshift-kni/performance-addon-operators#404]
From https://github.com/openshift-kni/performance-addon-operators/blob/master/docs/cpu-load-balancing.md:

```
Functionality to disable/enable the CPU load balancing will be implemented on the CRI-O level, the code under the CRI-O will disable/enable CPU load balancing only when:

the pod uses performance-<profile_name> runtime class
the pod has cpu-load-balancing.crio.io: true annotation
```

"will enable/disable only when" does not make sense.  Furthermore, having a key of "cpu-load-balancing.crio.io" would IMO indicate to most that setting this to "true" would *enable* load-balancing.  Can we get clarity on what:

cpu-load-balancing.crio.io: true

actually does?  Does this disable load-balancing, or keep load-balancing enabled?  If the former, shouldn't the key have been:

disable-cpu-load-balancing.crio.io: true

?

**Comment by cynepco3hahue** [comment]
yep exactly, but to change it, we firstly should to change it under the cri-o

**Comment by MarSik** [comment]
This is being addressed in https://github.com/cri-o/cri-o/pull/4389

**Comment by cynepco3hahue** [comment]
@atheurer You can use `cpu-load-balancing.crio.io: disable` to disable the CPU load balancing.

**Comment by atheurer** [comment]
Excellent, thanks.
