### ISSUE TITLE
Generate client set for our API

### ISSUE THREAD

**Issue by cynepco3hahue** [openshift-kni/performance-addon-operators#63]
It possible situation when we want to get a performance profile via API, for example, to make our functional test less dependent on the hard-coded configuration, but currently, it does not possible, because that we do not have client set for performance profile resources.

NOTE:
I believe we can get performance profile resources via the REST client, but I prefer to avoid it and work with the API.

**Comment by slintes** [comment]
resolved by https://github.com/openshift-kni/performance-addon-operators/pull/69
