### ISSUE TITLE
augment gather_sysinfo to collect machineinfo data

### ISSUE THREAD

**Issue by fromanirh** [openshift-kni/performance-addon-operators#756]
`gather_sysinfo` should collect machineinfo data in the `sysinfo.tgz` it produces. We can use this package: https://github.com/openshift-kni/debug-tools/tree/main/pkg/machineinformer
The data should be stored in `/etc/machineinfo/machineinfo.json`

**Comment by marioferh** [comment]
Completed: https://github.com/openshift-kni/performance-addon-operators/pull/781
